### ISSUE TITLE
Create Layout Ideas UI/UX for the Firefly vote module

### ISSUE THREAD

**Issue by Phyloiota** [iota-community/Community-Governance#42]
Step by step lets define how it should look and what a user should do to vote in Firefly

**Comment by adamkundrat** [comment]
Feedback for the layout starts here: https://discord.com/channels/397872799483428865/853248225767063592/863102986749476895

**Next:**
- [ ] develop alternative flows
- [ ] work on language

fyi @frnfa

**Comment by Phyloiota** [comment]
Oh sorry Adam, just saw the comments. I will start doing more in that Repo now, lets start working properly here!

**Comment by adamkundrat** [comment]
Based on my discussion @Phyloiota, few notes:
- add support for multiple options (inc. brief text about it)
- we agreed that the amount does not have to be editable
- we need improve to make it clear user is not spending any funds
- there was a discussion to add support for ability to spread the votes...i.e. if user does not want to vote with whole balance in the same time but wants to spread it over time -> _This is parked for now._ -> 
- alternative flows will be parked for now until we agree to main flow.

**Comment by Phyloiota** [comment]
> Based on my discussion @Phyloiota, few notes:
> 
> * add support for multiple options (inc. brief text about it)
> * we agreed that the amount does not have to be editable
> * we need improve to make it clear user is not spending any funds
> * there was a discussion to add support for ability to spread the votes...i.e. if user does not want to vote with whole balance in the same time but wants to spread it over time -> _This is parked for now._ ->
> * alternative flows will be parked for now until we agree to main flow.

You know what would be awesome... if we could create one, or a few little animated how-to videos... 45 seconds that hit those bullet points with a nice graphical explanation..... graphic skills needed...

**Comment by adamkundrat** [comment]
that would be awesome! I think we might even know some talent that could pull this but for $$. Let's keep talking and list the ideas here so start to compile list and once we agree it's final we can start looking for ppl that can do various things.
